### ISSUE TITLE
Very distorted sound

### ISSUE THREAD

**Issue by Ravens62** [project-owner/Peppy.doc#14]
Hi,
I don't know if I do something wrong, but when I try to use some preset equalizer I get a very distorted sound. Even if I mark the editable, the sound quality does not improve much.
I use:
Raspbery Pi 4B
HIFIBERRY AMP2
WaveShare 4.3 "DSI display
Van gogh headles

**Comment by project-owner** [comment]
Hi,

I assembled the setup with Pi 4 and Amp2 and was able to reproduce the issue.
I'm not sure what could be the root cause. I asked the question on the HiFiBerry forum:
https://support.hifiberry.com/hc/en-us/community/posts/6410377267473-Distortions-in-Pi-4-Amp2-Equalizer
Hopefully they will reply.

Best regards

**Comment by project-owner** [comment]
Hi,

They replied that equalizer plugin doesn't work well with amplifier.
Anyway, you can try to reduce the default and other equalizer presets in the file /home/pi/Peppy/util/util.py:
https://github.com/project-owner/Peppy/blob/c64f40c3a34d8917c0232a29ed598cc03b85168d/util/util.py#L74

Best regards

**Comment by Ravens62** [comment]
Hi,
This has helped to reduce the base level to 55, the sound is no longer distorted. And I tried to download all the equalizers and the sound is better, but it's much less loud. But with good speakers it is enough :-)

It seems that as a level of above 60 increases, the signal amplification begins to pass through the amplifier.
